#ifndef CONFIG_H
#define CONFIG_H

#define INTERRUPT_MANAGER_UPDATE_INTERVAL_MS 10
#define POMODORO_TIMER_UPDATE_INTERVAL_MS 1000
#define LED_BAR_UPDATE_INTERVAL_MS 10

#define LED_BAR_PROGRESS_BAR_MAX_VALUE 1500
#define PWM_MAX_VALUE 255

#define POMODORO_TIMER_WORK_MODE_TIME_S (25*60)
#define POMODORO_TIMER_BREAK_MODE_TIME_S (5*60)
#define POMODORO_TIMER_BREAK_TIME_TO_PROGRESS (POMODORO_TIMER_WORK_MODE_TIME_S / POMODORO_TIMER_BREAK_MODE_TIME_S)

#define BUTTON_PRESS_SHORT_MAX_LENGTH_MS 800

// IO config
#define GREEN_LED_PIN GPIO_Pin_3
#define RED_LED_PIN GPIO_Pin_4
#define DEBUG_1_CHANNEL_PIN GPIO_Pin_7
#define DEBUG_2_CHANNEL_PIN GPIO_Pin_6
#define DEBUG_3_CHANNEL_PIN GPIO_Pin_4
#define DEBUG_4_CHANNEL_PIN GPIO_Pin_5

#define BUZZER_PORT GPIOB
#define BUZZER_PIN GPIO_Pin_1

#define BUTTON_PORT GPIOA
#define BUTTON_PIN GPIO_Pin_2

#define UART_BAUDRATE 57600

// BEEPING CONFIG
#define SHORT_BEEP_DURATION 50
#define MEDIUM_BEEP_DURATION 500
#define LONG_BEEP_DURATION 500
#define DEFAULT_BUZZER_OFF_DELAY 400

#endif