#ifndef CONFIG_H
#define CONFIG_H

#define POMODORO_TIMER_UPDATE_INTERVAL_MS 10
#define LED_BAR_UPDATE_INTERVAL_MS 10

#define LED_BAR_PROGRESS_BAR_MAX_VALUE 1500

#define POMODORO_TIMER_WORK_MODE_TIME_S (25*60)
#define POMODORO_TIMER_BREAK_MODE_TIME_S (5*60)

#endif